In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("Salary_Data.csv")
dataset

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

## linear regression

In [3]:
x = dataset.iloc[:, :-1].values

y = dataset.iloc[:, -1].values

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 10)
x_train, x_test, y_test

(array([[ 4.1],
        [ 9.6],
        [ 4. ],
        [ 1.3],
        [ 6. ],
        [ 4.5],
        [ 5.9],
        [ 3. ],
        [ 4. ],
        [ 8.2],
        [ 8.7],
        [10.3],
        [ 7.9],
        [ 3.9],
        [ 9.5],
        [10.5],
        [ 3.2],
        [ 9. ],
        [ 5.1],
        [ 5.3],
        [ 1.1],
        [ 4.9],
        [ 2.2],
        [ 3.7]]),
 array([[6.8],
        [3.2],
        [2.9],
        [1.5],
        [2. ],
        [7.1]]),
 array([91738., 54445., 56642., 37731., 43525., 98273.]))

In [5]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [7]:
y_pred = regressor.predict(x_test)
y_pred


array([89715.76498848, 56031.05821174, 53223.99931368, 40124.39112273,
       44802.8226195 , 92522.82388655])

In [8]:
y_test

array([91738., 54445., 56642., 37731., 43525., 98273.])

In [9]:
x_test

array([[6.8],
       [3.2],
       [2.9],
       [1.5],
       [2. ],
       [7.1]])

In [10]:
diff=(y_pred-y_test)
diff


array([-2022.23501152,  1586.05821174, -3418.00068632,  2393.39112273,
        1277.8226195 , -5750.17611345])

In [26]:
pd.DataFrame(np.c_[y_test, y_pred, diff],columns=["Actual_value", "Predicted_value","Diff"])

Actual_value  Predicted_value         Diff
0       91738.0     92048.390000 -2022.235012
1       54445.0     62903.551667  1586.058212
2       56642.0     59388.195000 -3418.000686
3       37731.0     44309.980000  2393.391123
4       43525.0     41756.740000  1277.822619
5       98273.0    101264.180000 -5750.176113

In [12]:
print("Train Accuracy:", regressor.score(x_train,y_train))
print("Test Accuracy:", regressor.score(x_test,y_pred))


Train Accuracy: 0.9494673013344644
Test Accuracy: 1.0


## Random forest

In [21]:
from sklearn.ensemble import RandomForestRegressor
reg = RandomForestRegressor()
reg.fit(x_train, y_train)

RandomForestRegressor()

In [22]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error



In [23]:
y_pred = reg.predict(x_test)
y_pred


array([ 92048.39      ,  62903.55166667,  59388.195     ,  44309.98      ,
        41756.74      , 101264.18      ])

In [24]:
pd.DataFrame(np.c_[y_test, y_pred, diff],columns=["Actual_value", "Predicted_value","Diff"])

Actual_value  Predicted_value         Diff
0       91738.0     92048.390000 -2022.235012
1       54445.0     62903.551667  1586.058212
2       56642.0     59388.195000 -3418.000686
3       37731.0     44309.980000  2393.391123
4       43525.0     41756.740000  1277.822619
5       98273.0    101264.180000 -5750.176113

In [25]:
print("Train Accuracy:", reg.score(x_train,y_train))
print("Test Accuracy:", reg.score(x_test,y_pred))


Train Accuracy: 0.9902527176543167
Test Accuracy: 1.0


## SVR

In [30]:
from sklearn.svm import SVR
reg1= SVR()
reg1.fit(x_train, y_train)

SVR()

In [31]:
import pandas as pd
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [38]:
y_pred = reg1.predict(x_test)
y_pred


array([66990.59291858, 66978.86908013, 66978.73154206, 66980.19780986,
       66979.35594653, 66991.55050697])

In [33]:
pd.DataFrame(np.c_[y_test, y_pred, diff],columns=["Actual_value", "Predicted_value","Diff"])

Actual_value  Predicted_value         Diff
0       91738.0     92048.390000 -2022.235012
1       54445.0     62903.551667  1586.058212
2       56642.0     59388.195000 -3418.000686
3       37731.0     44309.980000  2393.391123
4       43525.0     41756.740000  1277.822619
5       98273.0    101264.180000 -5750.176113

In [35]:
print("Train Accuracy:", reg1.score(x_train,y_train))
print("Test Accuracy:", reg1.score(x_test,y_pred))


Train Accuracy: -0.20029476981329108
Test Accuracy: 0.00045160863461157774


## DECISION TREE

In [36]:
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error


In [37]:
from sklearn.svm import SVR
reg2= DecisionTreeRegressor()
reg2.fit(x_train, y_train)

DecisionTreeRegressor()

In [39]:
y_pred = reg2.predict(x_test)
y_pred


array([ 93940.,  64445.,  60150.,  46205.,  39891., 101302.])

In [40]:
pd.DataFrame(np.c_[y_test, y_pred, diff],columns=["Actual_value", "Predicted_value","Diff"])

Actual_value  Predicted_value         Diff
0       91738.0          93940.0 -2022.235012
1       54445.0          64445.0  1586.058212
2       56642.0          60150.0 -3418.000686
3       37731.0          46205.0  2393.391123
4       43525.0          39891.0  1277.822619
5       98273.0         101302.0 -5750.176113

In [41]:
print("Train Accuracy:", reg2.score(x_train,y_train))
print("Test Accuracy:", reg2.score(x_test,y_pred))


Train Accuracy: 0.9999612803278585
Test Accuracy: 1.0
